# Generated by Django 5.0 on 2023-12-11 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libreria", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="libro",
            old_name="decription",
            new_name="descripcion",
        ),
    ]
