# Generated by Django 5.0 on 2023-12-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libreria", "0003_equipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="imagen",
            field=models.ImageField(
                null=True, upload_to="imagenes/", verbose_name="Imagen_Equipo"
            ),
        ),
    ]
